services:
  mywebsite:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mywebsite
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # GitHub Models API (OpenAI)
      - GITHUB_MODELS_TOKEN=${GITHUB_MODELS_TOKEN}
      - GITHUB_MODELS_MODEL=${GITHUB_MODELS_MODEL:-openai/gpt-4o}

      # GitHub API for fetching repositories
      - GITHUB_PUBLIC_USERNAME=${GITHUB_PUBLIC_USERNAME}
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}

      # MinIO/S3 Configuration
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - MINIO_REGION=${MINIO_REGION:-us-east-1}
      - MINIO_FORCE_PATH_STYLE=${MINIO_FORCE_PATH_STYLE:-true}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}

      # Resend (Email Service)
      - RESEND_API_KEY=${RESEND_API_KEY}

      # Next.js
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - mywebsite-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mywebsite-network:
    driver: bridge
